---

spring:
  application:
    name: LoLjoa-Server

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: pass

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

---