---

spring:
  application:
    name: LoLjoa-Server

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/loljoa
    username: ladmin
    password: pass

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

---